#!/bin/bash

# Determine if pi has IP
networkConnected() {
  WLAN0=$(ip link ls dev wlan0 | grep "state UP")
  ETH0=$(ip link ls dev eth0 | grep "state UP")

  if [ "$ETH0" = "" ] && [ "$WLAN0" = "" ]; then
    return 1  # False
  else
    return 0  # True
  fi
}

# Check for 10s of downtime
if ! networkConnected; then
  sleep 10
  if ! networkConnected; then
    $(create_ap -n wlan0 pifi password --no-virt)
  fi
fi
